name: Node

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    lint-js:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Install Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24

            - name: Install dependencies
              run: npm install

            - name: Run Lint
              run: npm run lint
